version: '3.7'

services:
  node_exporter:
    container_name: node_exporter
    image: prom/node-exporter
    restart: always
    ports:
    - 9100:9100
    networks:
      - base_net
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    ports:
    - 9090:9090
    networks:
      - base_net
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    ports:
    - 3456:3000
    networks:
      - base_net

networks:
  base_net:
    external: true