version: '3.7'
services:
  rabbitmq-docker:
    image: rabbitmq:${RABBITMQ_IMAGE_VERSION}
    restart: on-failure
    container_name: rabbitmq-docker
    environment:
        - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
        - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
        # AMQP protocol port
        - 5672:5672
        # HTTP management UI
        - 15672:15672
    volumes:
        - ./data:/var/lib/rabbitmq/
        - ./log:/var/log/rabbitmq/ #./log permission must 777 (chmod -R 777 ./log)