version: '3.7'
services:
  mongodb:
    image: mongo:${MONGO_IMAGE_VERSION}
    restart: unless-stopped
    container_name: mongodb
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "100m"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "2"
    #       memory: "1G"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    networks:
      - base_net
networks:
  base_net:
    external: true