version: '3.7'
services:
  mongodb-4.0.16-xenial:
    image: mongo:4.0.16-xenial
    restart: unless-stopped
    container_name: mongodb-4.0.16-xenial
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "100m"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "2"
    #       memory: "1G"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27018:27018
    volumes:
      - ./data-4.0.16-xenial/db:/data/db
    networks:
      - base_net
networks:
  base_net:
    external: true