version: '3.7'
services:
  wordpress-docker:
    image: wordpress:latest
    restart: unless-stopped
    container_name: wordpress-docker
    volumes:
      - ./data:/var/www/html
    ports:
      - 8081:80
    environment:
      - WORDPRESS_DB_HOST=mysql-docker
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=mickeymouse
      - WORDPRESS_DB_NAME=test
    networks:
      - base_net
networks:
  base_net:
    external: true