version: '3.7'
services:
  clickhousedb-docker:
    image: clickhouse/clickhouse-server
    container_name: clickhousedb-docker
    hostname: clickhousedb-docker
    environment:
      CLICKHOUSE_USER: "mickey"
      CLICKHOUSE_PASSWORD: "mouse"
    volumes:
      - ./data/db/lib/:/var/lib/clickhouse
    ports:
      - "8123:8123" # HTTP interface
      - "9010:9000" # Native client interface
    networks:
      - base_net
networks:
  base_net:
    external: true