version: '3.7'
services:
  mysql-docker:
    image: mysql:${MYSQL_IMAGE_VERSION}
    # image: percona/percona-server:8.0
    restart: unless-stopped
    container_name: mysql-docker
    command: 'mysqld --sql_mode='
    # command: "mysqld --default-authentication-plugin=mysql_native_password --sql-mode="
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - base_net
networks:
  base_net:
    external: true